#!/bin/bash

# This script is to be used when opening files from the terminal. It dissociates the new window and the terminal, allowing the latter to be closed without closing the former.
if [ $# -ne 1 ] ; then
	echo "Missing file to open"
       	exit 1
fi

{ nohup xdg-open "$1" & } ; exit
